name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  PACKAGE_NAME: appcat

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_yaml
          - lint_adoc
          - lint_commodore
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: "check"
