
apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod
spec:
  parameters:
    backup:
      schedule: '*/1 * * * *'
    service:
      majorVersion: "15"
      pgSettings:
        timezone: Europe/Zurich
    size:
      cpu: "600m"
      memory: "100Mi"
      disk: "2Gi"
  writeConnectionSecretToRef:
    name: postgres-creds

# apiVersion: vshn.appcat.vshn.io/v1
# kind: VSHNPostgreSQL
# metadata:
#   name: pgsql-app2-prod
# spec:
#   parameters:
#     restore:
#       claimName: pgsql-app1-prod
#       backupName: # k get sgbackups --all-namespaces
#     backup:
#       schedule: '0 22 * * *'
#     service:
#       majorVersion: "15"
#       pgSettings:
#         timezone: Europe/Zurich
#     size:
#       cpu: "600m"
#       memory: "100Mi"
#       disk: "2Gi"
#   writeConnectionSecretToRef:
#     name: postgres-creds-restored
#   compositionRef:
#     name: vshnpostgresrestore.vshn.appcat.vshn.io

