name: Component
on:
  pull_request:
    branches:
      - master
    paths:
      - component/**

env:
  COMPONENT_NAME: appcat

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}/component
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Compile component
        run: make test -e instance=${{ matrix.instance }}

  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}/component
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
