name: Docs
on:
  pull_request:
    branches:
      - master
    paths:
      - docs/**

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint_adoc
        run: make lint_adoc
