name: E2E
on:
  # allow manual triggers
  workflow_dispatch: {}
  schedule:
    # daily midnight
    - cron: '0 0 * * *'
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get KUBECONFIG
        shell: bash
        env:
          LAB_KUBECONFIG: ${{ secrets.LAB_KUBECONFIG }}
        run: |
          echo "$LAB_KUBECONFIG" > kubeconfig
      - name: Run tests
        run: make e2e-test
        env:
          KUBECONFIG: kubeconfig
