name: Package
on:
  pull_request:
    branches:
      - master
    paths:
      - packages/**

env:
  PACKAGE_SUBDIR: packages

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - provider-cloudscale
          - provider-exoscale
          - composite-objectstorage-cloudscale
          - composite-objectstorage-exoscale
          - composition-objectstorage-cloudscale
          - composition-objectstorage-exoscale
          - composition-dbaas-postgres-exoscale
          - composition-dbaas-mysql-exoscale
          - composition-dbaas-redis-exoscale
          - composition-dbaas-kafka-exoscale
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_SUBDIR }}
    steps:

      - uses: actions/checkout@v3

      - name: Compile package
        run: make test -e instance=${{ matrix.instance }}

  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - provider-cloudscale
          - provider-exoscale
          - composite-objectstorage-cloudscale
          - composite-objectstorage-exoscale
          - composition-objectstorage-cloudscale
          - composition-objectstorage-exoscale
          - composition-dbaas-postgres-exoscale
          - composition-dbaas-mysql-exoscale
          - composition-dbaas-redis-exoscale
          - composition-dbaas-kafka-exoscale
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_SUBDIR }}
    steps:

      - uses: actions/checkout@v3

      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
